telegram:
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: DEV
    direction: both
    telegram:
      chatId: -1001389294904
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '914969065339093113'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
  - name: APE
    direction: both
    telegram:
      chatId: -1001128030094  
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '925766631358070784'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
  - name: DeFi
    direction: both
    telegram:
      chatId: -1001159575520  # maj ok
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '925464078292488212'       # maj ok
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
  - name: Trading
    direction: both
    telegram:
      chatId: -1001263677450    # maj ok 
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '925826513146892339'       # maj ok
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
debug: true
